### ISSUE TITLE
client: deploy and integrate with Vercel

### ISSUE THREAD

**Issue by AaronCQL** [CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15#30]

**Comment by EugeneTeu** [comment]
This one is deployment on vercel for client side only right

**Comment by AaronCQL** [comment]
@EugeneTeu yes, together with CD

**Comment by EugeneTeu** [comment]
![Screenshot 2020-10-12 at 2 08 55 AM](https://user-images.githubusercontent.com/43085751/95686366-ed599780-0c2f-11eb-8ec8-cce10c76bdad.png)


@AaronCQL do we need to request permission again we do right

**Comment by AaronCQL** [comment]
> @AaronCQL do we need to request permission again we do right

Yes, in order for the Vercel bot to integrate fully for CD
