### ISSUE TITLE
client: fix SEO handling when displaying questions/answers from Next server

### ISSUE THREAD

**Issue by AaronCQL** [CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15#50]
Flow:

1. Next server gets questions and answers documents from API server
2. Next server renders the markdown to HTML (or API server generates HTML from markdown in step 1)
3. Next serves the page to client with the rendered HTML
4. Client loads the required markdown editor if needed (ie. when user wants to edit)

**Comment by EugeneTeu** [comment]
@AaronCQL this is fixed right can close
