### ISSUE TITLE
client: shift query of all questions in user to server

### ISSUE THREAD

**Issue by AaronCQL** [CS3219-SE-Principles-and-Patterns/cs3219-ay2021-s1-project-2020-s1-g15#65]
- Only query all questions when it is needed (ie. when visiting user page for statistics)
- Querying of all questions should be done by backend via `/api/users/:id/questions` in `users` controller instead of the client querying GET for all the questions IDs in the user

**Comment by EugeneTeu** [comment]
this one should be together when i obtain user object or i have a separate endpoint for `questions` `answers` `analysis`. If its the latter then the frontend should do a fetch `user` - render - fetch `questions ` - render
